sudo: no
language: python
python:
  - 2.7
  - 3.4
  - 3.5
install:
  - pip install -r requirements/production.txt
  - pip install coveralls
script:
  - cd djangomx
  - python manage.py test
after_success:
  - coveralls
