sudo: no
language: python
python:
  - 2.7
install:
  - pip install -r requirements/development.txt
  - pip install coveralls
script:
  - cd djangomx
  - python manage.py test
after_success:
  - coveralls
